const ALL_QUESTIONS = [
    {
        diff: "easy",
        cat: "web",
        q: "What is the Internet?",
        opts: [
            "A service for delivering web pages via HTTP",
            "A global network connecting computers to each other",
            "A programming language used by browsers",
            "A type of web server software",
        ],
        ans: 1,
        exp: "The **Internet** is a global network of interconnected computers. The **Web** is a service built ON TOP of the Internet that uses HTTP to deliver documents.",
    },
    {
        diff: "easy",
        cat: "web",
        q: "Which analogy best describes the relationship between the Internet and the Web?",
        opts: [
            "The Internet is the courier; the Web is the road",
            "The Internet is the road; the Web is the courier service",
            "They are exactly the same thing",
            "The Internet is the browser; the Web is the server",
        ],
        ans: 1,
        exp: "The **road** = Internet (physical infrastructure). The **courier** = Web (the service that transports documents using HTTP over that infrastructure).",
    },
    {
        diff: "easy",
        cat: "web",
        q: "What does HTTP stand for?",
        opts: [
            "HyperText Transfer Protocol",
            "Hyper Transfer Text Protocol",
            "HyperText Transport Program",
            "High Transfer Text Protocol",
        ],
        ans: 0,
        exp: "**HTTP** = HyperText Transfer Protocol. It is the agreed set of rules (protocol) for communication between a client (browser) and a server.",
    },
    {
        diff: "medium",
        cat: "web",
        q: "What does DNS stand for and what does it do?",
        opts: [
            "Dynamic Name Service — assigns IPs automatically",
            "Domain Name System — maps domain names to IP addresses",
            "Data Network Server — routes network traffic",
            "Domain Node System — connects browser to server",
        ],
        ans: 1,
        exp: "**DNS** = Domain Name System. It works like a phone book: it translates a human-readable domain (e.g. google.com) into the **IP address** of the server.",
    },
    {
        diff: "medium",
        cat: "web",
        q: "When you type 'udemy.com' into a browser, what is the FIRST thing that happens?",
        opts: [
            "The browser sends a GET request to udemy.com",
            "The browser queries DNS to find the IP address",
            "The server sends back an HTML file",
            "The browser renders the page",
        ],
        ans: 1,
        exp: "First, the browser asks **DNS** to translate the domain into an IP address. Only after getting the IP can the browser send an **HTTP request**.",
    },
    {
        diff: "easy",
        cat: "web",
        q: "Which of the following is NOT a capability of a web browser?",
        opts: [
            "Sending HTTP requests",
            "Rendering HTML and CSS",
            "Hosting a database",
            "Processing JavaScript",
        ],
        ans: 2,
        exp: "Browsers can request, receive, and display content. **Hosting a database** is a server-side (back-end) responsibility.",
    },
    {
        diff: "easy",
        cat: "concept",
        q: "Which of the following is a BACK-END technology?",
        opts: [
            "HTML5",
            "CSS3",
            "JavaScript in the browser",
            "Python with Django",
        ],
        ans: 3,
        exp: "**Python with Django** runs on the server (back-end). HTML, CSS, and client-side JS are front-end technologies.",
    },
    {
        diff: "medium",
        cat: "concept",
        q: "What is a static website?",
        opts: [
            "A website with no images or animations",
            "A website whose files are sent directly from the server without transformation",
            "A website that never changes its design",
            "A website that doesn't use JavaScript",
        ],
        ans: 1,
        exp: "A **static website** sends pre-built files directly. Dynamic websites generate content on-the-fly using back-end languages.",
    },
    {
        diff: "medium",
        cat: "html",
        q: "In the analogy 'The GREEN ALIEN DANCES', what does ALIEN represent?",
        opts: [
            "CSS — the adjective (appearance)",
            "HTML — the noun (content/structure)",
            "JavaScript — the verb (behavior)",
            "HTTP — the protocol",
        ],
        ans: 1,
        exp: "**ALIEN** = HTML (the noun). **GREEN** = CSS (the adjective). **DANCES** = JavaScript (the verb).",
    },
    {
        diff: "easy",
        cat: "html",
        q: "What is the correct order of elements in a basic HTML document?",
        opts: [
            "`<!DOCTYPE>` → `<body>` → `<head>` → `<html>`",
            "`<!DOCTYPE>` → `<html>` → `<head>` → `<body>`",
            "`<html>` → `<!DOCTYPE>` → `<head>` → `<body>`",
            "`<head>` → `<body>` → `<html>` → `<!DOCTYPE>`",
        ],
        ans: 1,
        exp: "The correct order is: `<!DOCTYPE html>` first, then `<html>` (root), then `<head>` (metadata), then `<body>` (content).",
    },
    {
        diff: "easy",
        cat: "html",
        q: "What does the `<head>` element contain?",
        opts: [
            "Visible page content like text and images",
            "Metadata, title, and resource links not shown on screen",
            "The navigation menu of the page",
            "Only the page title",
        ],
        ans: 1,
        exp: "The `<head>` contains **metadata**, the `<title>`, and links to CSS. It is NOT displayed on the page itself.",
    },
    {
        diff: "medium",
        cat: "html",
        q: "How many times should you use `<h1>` on a single webpage?",
        opts: [
            "As many times as needed",
            "Maximum of 6 times",
            "Only once",
            "Never — use <h2> instead",
        ],
        ans: 2,
        exp: "`<h1>` should appear only **ONCE** per page. It represents the main topic and is crucial for SEO.",
    },
    {
        diff: "easy",
        cat: "html",
        q: "Which HTML element structure is CORRECT?",
        opts: [
            "`<p>Hello World<p>`",
            "`</p>Hello World</p>`",
            "`<p>Hello World</p>`",
            "`<p>Hello World>`",
        ],
        ans: 2,
        exp: "Correct HTML requires an **opening tag** `<p>`, content, and a **closing tag** `</p>` with a forward slash.",
    },
    {
        diff: "medium",
        cat: "html",
        q: "Which of these is a BLOCK-level element?",
        opts: ["`<span>`", "`<strong>`", "`<em>`", "`<div>`"],
        ans: 3,
        exp: "`<div>` is a **block-level** element. `<span>`, `<strong>`, and `<em>` are **inline** elements.",
    },
    {
        diff: "medium",
        cat: "html",
        q: "What is the difference between `<b>` and `<strong>`?",
        opts: [
            "They are completely identical",
            "`<b>` is visual bold only; `<strong>` adds semantic importance",
            "`<strong>` is deprecated in HTML5",
            "`<b>` is for headings; `<strong>` is for paragraphs",
        ],
        ans: 1,
        exp: "`<b>` is visual. `<strong>` adds **semantic meaning** — it tells browsers/screen readers that the text is important.",
    },
    {
        diff: "easy",
        cat: "html",
        q: "Which list type should you use for a set of cooking steps where ORDER matters?",
        opts: [
            "`<ul>` — Unordered List",
            "`<ol>` — Ordered List",
            "`<dl>` — Description List",
            "`<li>` — List Item",
        ],
        ans: 1,
        exp: "`<ol>` (**Ordered List**) is used when sequence matters. `<ul>` is for bullet points where order doesn't matter.",
    },
    {
        diff: "easy",
        cat: "html",
        q: "What is the purpose of the href attribute in an `<a>` tag?",
        opts: [
            "Sets the text color of the link",
            "Specifies the URL destination of the link",
            "Creates a tooltip on hover",
            "Opens the link in a new tab",
        ],
        ans: 1,
        exp: "**href** (Hypertext Reference) specifies WHERE the link navigates to.",
    },
    {
        diff: "easy",
        cat: "html",
        q: "Where must an HTML attribute always be placed?",
        opts: [
            "Inside the closing tag",
            "After the element content",
            "Inside the opening tag",
            "On a separate line below the tag",
        ],
        ans: 2,
        exp: 'Attributes are ALWAYS placed inside the **opening tag**. Example: `<h1 style="color:red">`.',
    },
    {
        diff: "medium",
        cat: "html",
        q: "You want to highlight a single word in a paragraph with a different color without breaking the line. Which element is best?",
        opts: ["`<div>`", "`<section>`", "`<span>`", "`<p>`"],
        ans: 2,
        exp: "`<span>` is an **inline container** perfect for styling text without breaking the flow. `<div>` would start a new line.",
    },
    {
        diff: "hard",
        cat: "html",
        q: "What is the correct meta tag for responsive design on mobile devices?",
        opts: [
            '`<meta name="mobile" content="responsive">`',
            '`<meta name="viewport" content="width=device-width, initial-scale=1.0">`',
            '`<meta charset="UTF-8">`',
            '`<meta name="screen" content="device-width">`',
        ],
        ans: 1,
        exp: "The **viewport** meta tag tells browsers to match the screen width of the device, enabling responsive design.",
    },
];
